name: presstartup
favicon: null
layout_spectrum: 0.1274028019979596
typography_spectrum: 0.1443038242869079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8067498800810426
  lightness: 0.6959732992108911
  saturation: 0.5363109165336937
  rhythmicContrast: 0.6923628831282258
purpose: []
