name: presstartup
favicon: null
layout_spectrum: 0.24723
typography_spectrum: 0.45127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332c2a'
    - '#71624e'
    - '#e1a791'
    - '#ffffff'
    - '#d26d4b'
  brandStrength: 0.8067498800810426
  lightness: 0.6959732992108911
  saturation: 0.5363109165336937
  rhythmicContrast: 0.6923628831282258
purpose: []
