name: presstartup
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4226638
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PresStartUp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c97a79'
    - '#000000'
    - '#855050'
    - '#c6c6c6'
  brandStrength: 0.8276047
  lightness: 0.6959732992108911
  saturation: 0.5363109165336937
  rhythmicContrast: 0.6923628831282258
purpose: []
